"""add episode table

Revision ID: 19489d428e56
Revises: 5a7128efa19
Create Date: 2013-10-25 18:27:14.953397
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '19489d428e56'
down_revision = '5a7128efa19'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['feed'], ['feed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episode')
    ### end Alembic commands ###
