"""user model

Revision ID: 20a1e1d7f7ae
Revises: None
Create Date: 2013-10-24 16:25:50.197057
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20a1e1d7f7ae'
down_revision = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
