"""feed model

Revision ID: 2753c3a2936d
Revises: 20a1e1d7f7ae
Create Date: 2013-10-24 16:33:41.838491
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2753c3a2936d'
down_revision = '20a1e1d7f7ae'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed')
    ### end Alembic commands ###
