"""non nullable columns

Revision ID: 2f649617dbca
Revises: b327ced0c52
Create Date: 2013-10-29 16:53:15.098221
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2f649617dbca'
down_revision = 'b327ced0c52'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episode', 'feed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('episode', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('feed', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('feed', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.SMALLINT(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('feed', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('feed', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('episode', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('episode', 'feed',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
