"""Subscription table

Revision ID: 471a7f4317f5
Revises: 2f649617dbca
Create Date: 2013-11-18 11:01:11.356153
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '471a7f4317f5'
down_revision = '2f649617dbca'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feed'], ['feed.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    ### end Alembic commands ###
