"""add password column

Revision ID: 5a7128efa19
Revises: 2753c3a2936d
Create Date: 2013-10-25 15:20:03.813138
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5a7128efa19'
down_revision = '2753c3a2936d'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    ### end Alembic commands ###
