"""add enclosure

Revision ID: b327ced0c52
Revises: 19489d428e56
Create Date: 2013-10-25 18:36:02.559023
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b327ced0c52'
down_revision = '19489d428e56'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('enclosure', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'enclosure')
    ### end Alembic commands ###
